### ISSUE TITLE
Determine whether Create Sample and Edit Sample forms need a Total Volume or Mass Sampled input

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/lili#129]
Need to make sense of the confusing TVS landscape and figure out if we need to add a field for entry or if this is calculated.

**Comment by BlakeDraper** [comment]
I think I have this figured out. The forms on the client have both method A of inputting sample volume (`meter_reading_initial + meter_reading final + meter_reading_unit`) and method B (`total_volume_sampled_initial + total_volume_sampled_unit_initial`).

Then, `total_volume_or_mass_sampled` gets calculated server-side. This all based on [this diagram](https://drive.google.com/file/d/0B_YnFzEvVI-7Q3V5Z1gwdXd2dTQ/edit) and this email from Joel: [](url)

> Blake,
> 
> TVS stands for total volume sampled.  There are two ways we can input a sample volume: 1) entering an initial and final meter reading (plus units)--LIMS calculates the sample volume as final minus initial, and 2) entering the volume (or mass) sampled (plus units) directly.  If the volume is input as gallons, LIMS converts to liters.
> 
> I'm not 100% sure, but I think the TVS_LITERS field is whatever was input with method 1 or 2 above converted to liters (which would be the sample volume used for calculating the final microbe concentration).
> 
> So, for sample volume there is:
> 1a.initial meter reading
> 1b. final meter reading
> 1c. units for meter readings
> 2a. total volume (mass) sampled
> 2.b units for total volume (mass) sampled
> 3. total volume sampled in liters (used for calculations)
> (See crude diagram)

@aaronstephenson can you just confirm that this is how sample volume is being handled on the web services end?

**Comment by aaronstephenson** [comment]
These fields are not being handled in any special way, aside from just accepting the submitted values (if they meet the data type requirements). This is exactly how we're handling similar updates, like dilution_factor for Inhibitions. The assumption was that the client would handle conversions if necessary.

**Comment by BlakeDraper** [comment]
We've made asses of u and me then. 
The basis for my assumption that the backend would handle this are:
1) you emailed Kathy Schoephoester asking about how those fields were handled
2) If the `total_volume_or_mass_sampled` is the ultimate goal and this is all handled on the client, then none of those other values would even need to be in the database, they could just be collected in a form and then only the `total_volume_or_mass_sampled` submitted. I don't know, maybe they want the raw values maintained for some reason.

**Comment by aaronstephenson** [comment]
1. Are you referring to the email from November 30? That was simply to get clarification on all the various fields, because the PATHLAB tables had far more than we do and they didn't have any obvious matches. The intent of the email was not to ask about calculations.
2. The primary reason we have the fields we do in the Sample table is because we determined those to be the fields necessary to run the LIMS, way back near the beginning of the project. I have never had some grand plan for these fields in particular, they've just been coming along for the ride. For the umpteenth time, this is exactly why I've been wanting to have a big review of the models file, to determine if the fields we have are absolutely necessary and if they've been defined correctly. If you want the web services to do a calculation, we can talk about that. In any case, raw values should be maintained in the database whenever possible to assist with future investigations.

**Comment by BlakeDraper** [comment]
1. Yes; ok. 
2. Agree. Can we do that this week? I hesitate to say it, but I think we might be at MVP for features now. So let's do our due diligence on that, deal with any fallout from that, and then I think we may actually be ready to pay them a visit. I just wrote the code to calculate `total_volume_or_mass_sampled` on the client side to submit with a sample POST, so we are covered now.

**Comment by aaronstephenson** [comment]
re: review, absolutely! Let's chat to schedule it.

**Comment by BlakeDraper** [comment]
Settled with PR #154
